### ISSUE TITLE
Android issue

### ISSUE THREAD

**Issue by kerimdemir** [JanPeter/RN-NavigationHeaderAnimation#5] opened 2018-05-28 14:07 UTC
![videotogif_2018 05 28_17 03 05](https://user-images.githubusercontent.com/19932626/40618230-8fe93f66-6299-11e8-962a-26be94742fca.gif)

**Comment by emmx** [comment] 2018-11-22 01:23
Could you fix this? I'm having the same issue. Duplicate of #4.

**Comment by JanPeter** [comment] 2018-12-06 10:19
Closing in favor of #4

**Closed as completed by JanPeter** 2018-12-06 10:19 UTC
